version: 2.1

orbs:
  python: circleci/python@1.5.0
  heroku: circleci/heroku@1.2.6

jobs:
  linting-and-test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run linting
          command: flake8
      - run:
          name: Run tests
          command: pytest

  save_docker-image-to-docker-hub:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - python/install-packages:
            pkg-manager: pip
      - setup_remote_docker:
          version: 20.10.11
      - run:
          name: Create and Push image to Docker Hub
          command: |
            TAG=$CIRCLE_BRANCH-$CIRCLE_SHA1
            docker login -u $DOCKER_USERNAME -p $DOCKER_TOKEN
            docker build . -t oclettings/p13_orange_county_app:$TAG
            docker tag oclettings/p13_orange_county_app:$TAG oclettings/p13_orange_county_app:latest
            docker push oclettings/p13_orange_county_app:$TAG
            docker push oclettings/p13_orange_county_app:latest

  deploy-on-heroku:
    executor: heroku/22
    steps:
      - checkout
      - heroku/install
      - setup_remote_docker:
            version: 20.10.11
            docker_layer_caching: true
      - run:
          name: Login to Heroku repository
          command: HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:login
      - run:
          name: Build and push docker image to Heroku repository
          command: HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:push -a $HEROKU_APP_NAME web
      - run:
          name: Release new version of the app on Heroku
          command: HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:release -a $HEROKU_APP_NAME web


workflows:

  deployment_process:
    jobs:
      - linting-and-test
      - save_docker-image-to-docker-hub:
          requires:
            - linting-and-test
          filters:
            branches:
              only:
                - master
      - deploy-on-heroku:
          requires:
            - save_docker-image-to-docker-hub
          filters:
            branches:
              only:
                - master
