version: 2.1

orbs:
  python: circleci/python@1.5.0
  heroku: circleci/heroku@1.2.6

jobs:
  linting-and-test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run linting
          command: flake8
      - run:
          name: Run tests
          command: pytest

  create-docker-image-and-push-to-hub:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - python/install-packages:
            pkg-manager: pip
      - setup_remote_docker:
          version: 20.10.11
      - run:
          name: Create docker image
          command: docker build . -t oclettings/p13_orange_county_app:$CIRCLE_BRANCH-$CIRCLE_SHA1
      - run:
          name: Log into Docker Hub
          command: docker login -u $DOCKER_USERNAME -p $DOCKER_TOKEN
      - run:
          name: Push image to Docker Hub
          command: docker push oclettings/p13_orange_county_app:$CIRCLE_BRANCH-$CIRCLE_SHA1

  deploy-on-heroku:
    executor: heroku/default
    steps:
      - checkout
      - setup_remote_docker:
            version: 20.10.11
      - heroku/install
      - heroku/push-docker-image
      - heroku/release-docker-image


workflows:

  deployment_process:
    jobs:
      - linting-and-test
      - create-docker-image-and-push-to-hub:
          requires:
            - linting-and-test
          filters:
            branches:
              only:
                - dev #changer pour master !!
      - deploy-on-heroku:
          requires:
            - create-docker-image-and-push-to-hub
          filters:
            branches:
              only:
                - dev #changer pour master !!
