version: 2.1

orbs:
  python: circleci/python@1.5.0
  heroku: circleci/heroku@1.2.6

jobs:
  linting-and-test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run linting
          command: flake8
      - run:
          name: Run tests
          command: pytest

  save_docker-image-to-docker-hub:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - python/install-packages:
            pkg-manager: pip
      - setup_remote_docker:
          version: 20.10.11
      - run:
          name: Create docker image
          command: docker build . -t oclettings/p13_orange_county_app:$CIRCLE_BRANCH-$CIRCLE_SHA1
      - run:
          name: Log into Docker Hub
          command: docker login -u $DOCKER_USERNAME -p $DOCKER_TOKEN
      - run:
          name: Push image to Docker Hub
          command: docker push oclettings/p13_orange_county_app:$CIRCLE_BRANCH-$CIRCLE_SHA1

  deploy-on-heroku:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - setup_remote_docker:
            version: 20.10.11
            docker_layer_caching: true
      - run:
          name: Deploy to Heroku
          command: |
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:login
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:push -a $HEROKU_APP_NAME web
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:release -a $HEROKU_APP_NAME web


workflows:

  deployment_process:
    jobs:
      - linting-and-test
      - save_docker-image-to-docker-hub:
          requires:
            - linting-and-test
          filters:
            branches:
              only:
                - master
      - deploy-on-heroku:
          requires:
            - save_docker-image-to-docker-hub
          filters:
            branches:
              only:
                - master
