version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  linting-and-test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run linting
          command: flake8
      - run:
          name: Run tests
          command: pytest

  create-docker-image-and-push-to-hub:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - python/install-packages:
            pkg-manager: pip
      - run:
          name: Create docker image
          command:
            docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
            docker build . -t oclettings/p13_orange_county_app:$CIRCLE_SHA1
      - run:
          name: Push image to Docker Hub
          command:
            docker push oclettings/p13_orange_county_app:$CIRCLE_SHA1

workflows:
  deploy-if-tests-passed:
    jobs:
      - linting-and-test
      - create-docker-image-and-push-to-hub
      requires:
        - linting-and-test
